branchr:
  # image: branchr
  build: .
  ports:
    - 3000:80
  links:
    - mongo
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $GIT_DIR:/git
    - $APP_COMPOSE:/root/docker-compose.yml
    # TODO: bring over ssh keys
    # TODO: set host if docker-machine
  environment:
    - MONGO_URL=mongodb://mongo/branchr
    - ROOT_URL=http://localhost
    - 'METEOR_SETTINGS=$METEOR_SETTINGS'

mongo:
  image: mongo:latest
