branchr:
  build: .
  ports:
    - 3000:80
  links:
    - mongo
  # privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $GIT_DIR:/git
    - $APP_COMPOSE:/tmp/app-compose.yml
    - $HOME/.ssh:/root/.ssh:ro
    # TODO: bring over ssh keys for private git repos
  environment:
    - MONGO_URL=mongodb://mongo/branchr
    - ROOT_URL=http://localhost
    - 'METEOR_SETTINGS=$METEOR_SETTINGS'

mongo:
  image: mongo:latest
