version: '2'

services:

  akita:
    extends:
      file: common.yml
      service: akita
    image: $IMAGE
    ports:
      - ${PORT_HTTP_AKITA}:80
      - ${PORT_HTTPS_AKITA}:443

  mailcatcher:
    extends:
      file: common.yml
      service: mailcatcher
    ports:
      - ${PORT_HTTP_MAILCATCHER}:1080

  nedcas:
    extends:
      file: common.yml
      service: nedcas
    ports:
      - ${PORT_HTTPS_CAS}:8443

  nedapi:
    extends:
      file: common.yml
      service: nedapi
    ports:
      - ${PORT_HTTP_NED}:8080
      - ${PORT_HTTPS_NED}:8443

  neddb:
    extends:
      file: common.yml
      service: neddb
